name: Build and run unit tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  install-and-test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Install npm dependencies
        run: |
          npm install
      - name: Run tests
        run: |
          npm test
